### ISSUE TITLE
Icons missing from ZMI

### ISSUE THREAD

**Issue by jordic** [zopefoundation/Zope#108]
I started working on and old zope codebase ( 2.13.19 ) and managed to update it to 2.13.24. 
Tried with newer versions without luck. ( I think that with 2.13.25 when boot I have conflicts with Product.Sessions).  But also, with 2.13.24 I miss the folder icons from the ZMI (any ideas how I can fix it)

**Comment by tseaver** [comment]
@jordic I'm sitting next to @dataflake, who says that 2.13.26 fixed the icons for his project.

**Comment by jordic** [comment]
yup! When trying to upgrade to 2.13.26 got this error:
```
2017-05-04 05:53:54 DEBUG ZEO.asyncio.client Stopping client thread
Traceback (most recent call last):
File "env/bin/runzope", line 11, in <module>
sys.exit(run())
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/Startup/run.py", line 22,in run
starter.prepare()
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/Startup/__init__.py", line 92, in prepare
self.startZope()
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/Startup/__init__.py", line 268, in startZope
Zope2.startup()
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/__init__.py", line 47, instartup
_startup()
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/App/startup.py", line 120, in startup
load_zcml()
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/App/startup.py", line 52,in load_zcml
load_site()
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Zope2/App/zcml.py", line 46, inload_site
_context = xmlconfig.file(site_zcml)
File "/home/jordi/Documents/zope/zdev/env/lib/python2.7/site-packages/zope/configuration/xmlconfig.py", line 500, in file
context.execute_actions()
File "/home/jordi/Documents/zope/zdev/env/lib/python2.7/site-packages/zope/configuration/config.py", line 363, in execute_actions
for action in resolveConflicts(self.actions):
File "/home/jordi/Documents/zope/zdev/env/lib/python2.7/site-packages/zope/configuration/config.py", line 916, in resolveConflicts
raise ConfigurationConflictError(conflicts)
zope.configuration.config.ConfigurationConflictError: Conflicting configuration actions
For: ('five:deprecatedManageAddDelete', <class 'Products.Sessions.BrowserIdManager.BrowserIdManager'>)
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Products/Sessions/configure.zcml", line 4.2-5.67
<five:deprecatedManageAddDelete
class="Products.Sessions.BrowserIdManager.BrowserIdManager"/>
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/OFS/deprecated.zcml", line 13.2-14.67
<five:deprecatedManageAddDelete
class="Products.Sessions.BrowserIdManager.BrowserIdManager"/>
For: ('five:deprecatedManageAddDelete', <class 'Products.Sessions.SessionDataManager.SessionDataManager'>)
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/Products/Sessions/configure.zcml", line 6.2-7.71
<five:deprecatedManageAddDelete
class="Products.Sessions.SessionDataManager.SessionDataManager"/>
File "/home/jordi/Documents/zope/zdev/env/local/lib/python2.7/site-packages/OFS/deprecated.zcml", line 15.2-16.71
<five:deprecatedManageAddDelete
class="Products.Sessions.SessionDataManager.SessionDataManager"/>
```
An really I'm noob here and can't figure out what should I do to solve it.

**Comment by mauritsvanrees** [comment]
You may be using a too new version of `Products.Sessions`. With Zope 2.13 you should use `Products.Sessions 3.0`. That is my first guess.

**Comment by jordic** [comment]
yup, works just installing Product.Sessions 3.0

requirements.txt
```
Products.Sessions==3.0
Zope2==2.13.26
Products.ZCTextIndex==2.13.1
python-gettext
z3c.sqlalchemy
DBUtils==1.1
psycopg2
```

But I still miss folder icons on ZMI. @tseaver @dataflake.
I can try to dig inside the package, if you point me in which O_O. And try to fix it.

PD: @mauritsvanrees Can't get why I have pulled Products.Sessions 4.0... :/

**Comment by jordic** [comment]
Seems like I missed to install  ``` Products.OFSP ```
After that, all icons from ZMI are in place :)
