### ISSUE TITLE
mkwsgiinstance utility invalid log paths in Windows

### ISSUE THREAD

**Issue by ewohnlich** [zopefoundation/Zope#1106]
### What I did:

Used the mkwsgiinstance command line script to make a wsgi instance.

### What I expect to happen:

Create a zope.ini etc

### What actually happened:

zope.ini contained invalid paths for [handler_accesslog] args and [handler_eventlog] args. Example:
`args = ('C:\Users\wohnlice\PycharmProjects\Plone6/var/log/event.log', 'a')` The backslashes need to be escaped on Windows otherwise it reads \U as a unicode value and throws an error.

### What version of Python and Zope/Addons I am using:

Windows 10, python 3.10, Zope2=4.0

**Comment by ewohnlich** [comment]
So my value for instancehome is 'C:\\Users\\wohnlice\\PycharmProjects\\Plone6', with backslashes already escaped. But when it gets printed to zope.ini it is like above.

Can fix this with: `instancehome = instancehome.replace('\\', '\\\\')`. Alternatively the zope.ini.in skel could probably be `args = (r'<<INSTANCE_HOME>>/var/log/event.log', 'a')` etc but I haven't tested this

**Comment by icemac** [comment]
@ewohnlich Thank you for reporting this issue. Could you please come up with a pull request – there are only very few people using Zope on Windows, so we do not have much expertise there.

**Comment by Meithal** [comment]
I added a 'r' before the problematic strings in the zope.ini file by hand and it fixed that issue

Now I have an other issue

```
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Desktop\zope\Zope-5.8.1\bin\runwsgi-script.py", line 93, in <module>
    sys.exit(Zope2.Startup.serve.main())
  File "c:\users\...\desktop\zope\zope-5.8.1\src\Zope2\Startup\serve.py", line 251, in main
    return command.run()
  File "c:\users\...\desktop\zope\zope-5.8.1\src\Zope2\Startup\serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "c:\users\...\desktop\zope\zope-5.8.1\src\Zope2\Startup\serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 270, in loadobj
    context = loadcontext(
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 295, in loadcontext
    return _loaders[scheme](
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 452, in get_context
    context = self._pipeline_app_context(
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 575, in _pipeline_app_context
    context.filter_contexts = [
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 576, in <listcomp>
    self.get_context(FILTER, name, global_conf) for name in pipeline[:-1]
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 461, in get_context
    context = self._context_from_use(
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 488, in _context_from_use
    context = self.get_context(object_type, name=use, global_conf=global_conf)
  File "c:\users\..\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 403, in get_context
    return loadcontext(
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 295, in loadcontext
    return _loaders[scheme](
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 638, in get_context
    entry_point, protocol, ep_name = self.find_egg_entry_point(
  File "c:\users\...\desktop\zope\zope-5.8.1\eggs\pastedeploy-3.0.1-py3.10.egg\paste\deploy\loadwsgi.py", line 658, in find_egg_entry_point
    dist = importlib_metadata.distribution(self.spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\importlib\metadata\__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\importlib\metadata\__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for Paste
```

**Comment by icemac** [comment]
@ewohnlich Could it be that `Paste` is not installed? Could you please paste the content of `C:\Users\Utilisateur\Desktop\zope\Zope-5.8.1\bin\runwsgi-script.py`?

**Comment by icemac** [comment]
@ewohnlich @Meithal Sorry for confusing you two in my previous comment.

**Comment by Meithal** [comment]
Sure

```
#!"C:\Users\Utilisateur\Desktop\zope\Zope-5.8.1\Scripts\python.exe"

import sys
sys.path[0:0] = [
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\develop\\accesscontrol\\src',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\acquisition-4.13-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\datetime-5.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\documenttemplate-4.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\extensionclass-5.0-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\multimapping-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\persistence-3.6-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zexceptions-4.3-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\src',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\five.localsitemanager-4.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\missing-4.2-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\products.btreefolder2-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\products.zcatalog-7.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\record-3.6-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.testing-5.0.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.schema-7.0.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.interface-5.5.2-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.globalrequest-1.6-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.dottedname-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.deferredimport-4.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zodb-5.8.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\develop\\restrictedpython\\src',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\btrees-5.0-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\lib\\site-packages',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.lifecycleevent-4.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.event-4.6-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.container-5.0-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope2-4.0-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.site-4.6.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.location-4.3-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.component-5.1.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\persistent-5.0-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\multipart-0.2.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.viewlet-4.3-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.traversing-4.4.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.testbrowser-5.6.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.tales-5.2-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.tal-5.0.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.size-4.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.sequencesort-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.security-6.1-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.publisher-6.1.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.ptresource-4.3.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.proxy-5.0.0-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.processlifetime-2.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.pagetemplate-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.i18nmessageid-5.1.1-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.i18n-4.9.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.exceptions-4.6-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.datetime-4.3.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.contenttype-4.6-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.contentprovider-4.2.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.configuration-4.4.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.browserresource-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.browserpage-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.browsermenu-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.browser-2.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\z3c.pt-3.3.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\waitress-2.1.2-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\transaction-3.0.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zconfig-3.6.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\pastedeploy-3.0.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\chameleon-3.10.2-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\six-1.16.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.structuredtext-4.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\roman-4.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\pytz-2022.7.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\authencoding-5.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zodbpickle-2.6-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zc.lockfile-3.0.post1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.filerepresentation-6.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.cachedescriptors-4.4-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.deprecation-4.4.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.annotation-4.8-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\zope.hookable-5.4-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\cffi-1.15.1-py3.10-win-amd64.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\wsgiproxy2-0.5.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\soupsieve-2.3.2.post1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\beautifulsoup4-4.11.2-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\webtest-3.0.0-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\python_gettext-4.1-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\pycparser-2.21-py3.10.egg',
  'c:\\users\\utilisateur\\desktop\\zope\\zope-5.8.1\\eggs\\webob-1.8.7-py3.10.egg',
  ]

import Zope2.Startup.serve

if __name__ == '__main__':
    sys.exit(Zope2.Startup.serve.main())
```

**Comment by icemac** [comment]
@Meithal How did you install `Zope`?
There was #735, which added the `wsgi` extra, so `Paste` gets installed.
See also the installation documentation:

* https://zope.readthedocs.io/en/latest/INSTALL.html#installing-zope-with-zc-buildout
* https://zope.readthedocs.io/en/latest/INSTALL.html#installing-zope-with-pip

**Comment by Meithal** [comment]
I used zc.buildout, this is my buildout.cfg

```
[buildout]
extensions = mr.developer
allow-picked-versions = false
develop = .
extends =
    sources.cfg
    versions.cfg
installed = .installed.cfg
parts =
    test
    zopescripts
    alltests
    allpy
    sphinx
    checkversions
    requirements
sources-dir = develop
auto-checkout =
    RestrictedPython
    AccessControl

[testenv]
PYTHONHASHSEED = random


[test]
recipe = zc.recipe.testrunner
script = test
environment = testenv
initialization =
    import sys
    import warnings
    warnings.simplefilter('default')
eggs = Zope


[zopescripts]
recipe = zc.recipe.egg
interpreter = zopepy
eggs =
    Zope[wsgi]


[alltests]
recipe = zc.recipe.testrunner
script = alltests
environment = testenv
eggs =
    AccessControl
    Acquisition
    DateTime
    DocumentTemplate
    ExtensionClass
    MultiMapping
    Persistence
    zExceptions
    Zope
# Test optional dependencies.
    five.localsitemanager
    Missing
    Products.BTreeFolder2
    Products.ZCatalog
    Record


[allpy]
recipe = zc.recipe.egg
eggs = ${alltests:eggs}
interpreter = allpy


[make-docs]
recipe = collective.recipe.template
input = inline:
    #!/bin/sh
    cd ${buildout:directory}/docs
    make html
output = ${buildout:directory}/bin/make-docs
mode = 755

[sphinx]
=> make-docs
recipe = zc.recipe.egg
eggs =
    Zope[docs]
    Sphinx
scripts =
    sphinx-build


[checkversions]
recipe = zc.recipe.egg
eggs = z3c.checkversions [buildout]


[requirements]
recipe = plone.recipe.command
command =
    ${zopescripts:bin-directory}/${zopescripts:interpreter} util.py
update-command = ${:command}
stop-on-error = yes
```

I take I have to add by hand Paste at the zopescripts section? I did that and run a buikdout command but still same error as above

**Comment by icemac** [comment]
@Meithal I think the `allpy` section in your buildout.cfg is the problem. It does not have `Zope[wsgi]` but just `Zope`, possibly overriding the generated run wsgi script.

Please minimise your `buildout.cfg` to just the `zopescripts` section to see if this helps. Afterwards you can re-add the sections you actually need, leaving out the ones you can live without.
