### ISSUE TITLE
Newly Installed Zope5 Fails on Startup (importlib.metadata)

### ISSUE THREAD

**Issue by sfluehnsdorf** [zopefoundation/Zope#1154]
Hi! I was trying to install Zope5 when I ran into an issue, I don't know how to fix. I believe it's related to importlib.metadata and Paste. Any help very much appreciated

Issue: Zope fails to start

Strictly followed instructions described on zope.readthedocs.io:
- Built-in standard buildout configuration
- Creating a Zope instance
- Running Zope in the foreground

Using:
MacOS Ventura
Python 3.11.5 (tried both shipped with OS and compiled from tarball)
Zope 5.8.4

Full Traceback:
```
Traceback (most recent call last):
  File "/Volumes/Scotty/sandbox/python3/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/bin/runwsgi", line 92, in <module>
    sys.exit(Zope2.Startup.serve.main())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/src/Zope2/Startup/serve.py", line 251, in main
    return command.run()
           ^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/src/Zope2/Startup/serve.py", line 189, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/src/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 248, in loadapp
    return loadobj(APP, uri, name=name, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 270, in loadobj
    context = loadcontext(
              ^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 295, in loadcontext
    return _loaders[scheme](
           ^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 452, in get_context
    context = self._pipeline_app_context(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 575, in _pipeline_app_context
    context.filter_contexts = [
                              ^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 576, in <listcomp>
    self.get_context(FILTER, name, global_conf) for name in pipeline[:-1]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 461, in get_context
    context = self._context_from_use(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 488, in _context_from_use
    context = self.get_context(object_type, name=use, global_conf=global_conf)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 403, in get_context
    return loadcontext(
           ^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 295, in loadcontext
    return _loaders[scheme](
           ^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 638, in get_context
    entry_point, protocol, ep_name = self.find_egg_entry_point(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/PasteDeploy-3.0.1-py3.11.egg/paste/deploy/loadwsgi.py", line 658, in find_egg_entry_point
    dist = importlib_metadata.distribution(self.spec)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/python3/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/python3/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for Paste
```

**Comment by d-maurer** [comment]
Sebastian F. Lühnsdorf wrote at 2023-9-14 12:15 -0700:
>Hi! I was trying to install Zope5 when I ran into an issue, I don't know how to fix. I believe it's related to importlib.metadata and Paste. Any help very much appreciated
> ...
>importlib.metadata.PackageNotFoundError: No package metadata was found for Paste


I am not using `buildout` but the `pip` based installation method.
For the latter, it is important to install `Zope[wsgi]` (rather than `Zope`).
I expect that something similar is necessary for `buildout`, too (e.g.
reference `Zope[wsgi]` (rather than `Zope`) in the `eggs` definition.

Apparently, `paste.deploy` (distribution name `PasteDeploy`) is available
in your installation but the `Paste` distribution seems missing.
Not sure how you got into this state.
If your `buildout` configuration file already uses `Zope[wsgi]` in
the `eggs` definition, you could try to add `Paste` as an additional egg
in this definition.

**Comment by dataflake** [comment]
Please see https://zope.readthedocs.io/en/latest/INSTALL.html#minimum-configuration - the minimal builsout configuration must include `Paste` explicitly.

**Comment by dataflake** [comment]
(And yes, the documentation changed a couple times over the last few days, apologies for that)

**Comment by sfluehnsdorf** [comment]
Paste is definitely installed, as well as PasteDeploy. I also followed the most current documentation.

I can reproduce the issue by installing Zope5 via pip. Also can reproduce the issue with the system's Python and with Python compiled from source.

Just tried installing Zope 5.7.3 and was successful, letting me believe it's related to a particular package's release. Will dig into this issue in the near future and will report my findings

**Comment by d-maurer** [comment]
Sebastian F. Lühnsdorf wrote at 2023-9-14 14:19 -0700:
> ...
>I can reproduce the issue by installing Zope5 via pip. Also can reproduce the issue with the system's Python and with Python compiled from source.

I just newly installed Zope via
```console
py310: pip install -e ../tmp/Zope'[wsgi]'
py310: mkwsgiinstance
...
py310: runwsgi etc/zope.ini
```
`../tmp/Zope` contains the current `Zope` `master`
(the upcoming Zope 5.8.5).

There were no startup problems.

**Comment by dataflake** [comment]
You said you used the built-in standard buildout configuration. Please see the note at https://zope.readthedocs.io/en/latest/INSTALL.html#built-in-standard-buildout-configuration - it is not meant for production and it does not install `Paste` in a way that it will be picked up by the `runwsgi` script created by `mkwsgiinstance`.

**Comment by sfluehnsdorf** [comment]
I tried "Custom buildout configurations" using the "Minimum configuration" as you suggested, but getting a wholly new exception:

```
sfl@defiant sandbox % python3.11 -m venv Zope-5.8.4        

sfl@defiant sandbox % cd Zope-5.8.4

sfl@defiant Zope-5.8.4 % cat << eol > buildout.cfg
heredoc> [buildout]
extends =
    https://zopefoundation.github.io/Zope/releases/5.0/versions-prod.cfg
parts =
    zopescripts

[zopescripts]
recipe = zc.recipe.egg
interpreter = zopepy
eggs =
    Zope
    Paste

heredoc> eol

sfl@defiant Zope-5.8.4 % bin/pip install -U pip wheel zc.buildout
Requirement already satisfied: pip in ./lib/python3.11/site-packages (23.2.1)
Collecting wheel
  Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
  Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
Collecting zc.buildout
  Using cached zc.buildout-3.0.1-py2.py3-none-any.whl (168 kB)
Requirement already satisfied: setuptools>=8.0 in ./lib/python3.11/site-packages (from zc.buildout) (68.1.2)
Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
Installing collected packages: wheel, zc.buildout
Successfully installed wheel-0.41.2 zc.buildout-3.0.1

sfl@defiant Zope-5.8.4 % bin/buildout 
Creating directory '/Volumes/Scotty/sandbox/Zope-5.8.4/eggs'.
Creating directory '/Volumes/Scotty/sandbox/Zope-5.8.4/parts'.
Creating directory '/Volumes/Scotty/sandbox/Zope-5.8.4/develop-eggs'.
root: Reading https://pypi.org/simple/zc.recipe.egg/
Getting distribution for 'zc.recipe.egg>=2.0.6'.
root: Downloading https://files.pythonhosted.org/packages/7a/6f/c6871e8490a153c3b44ac43e4a6552d802561a12b4780c7ea088a7ec5ff0/zc.recipe.egg-2.0.7.tar.gz#sha256=b89eb00979614e3584bb4e8431172b2345d00b983a04ebf00a401fb695f4e6d3
Got zc.recipe.egg 2.0.7.
Installing zopescripts.
root: Reading https://pypi.org/simple/Zope/
Getting distribution for 'Zope==5.0'.
root: Downloading https://files.pythonhosted.org/packages/65/05/1cb788c75ace2f3aabc09b7233d03f5c383d7a26eef61a389c5ff6a90c3e/Zope-5.0-py3-none-any.whl#sha256=46153ff95d8bb80606432e88e7eedff227326b882c63a9d75bbe5e010ae6ecf9
Got Zope 5.0.
root: Reading https://pypi.org/simple/Paste/
Getting distribution for 'Paste==3.4.1'.
root: Downloading https://files.pythonhosted.org/packages/cc/1b/ddb3d6467204709b53eb237196fa9d9da723805bbdf48328df34c2aef6aa/Paste-3.4.1-py2.py3-none-any.whl#sha256=5cc1250389b4e4003038f6ff6557ccfb7e8ba1dd0235529a31bc444de189cead
Got Paste 3.4.1.
root: Reading https://pypi.org/simple/six/
Getting distribution for 'six==1.15.0'.
root: Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl#sha256=8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced
Got six 1.15.0.
root: Reading https://pypi.org/simple/zope.viewlet/
Getting distribution for 'zope.viewlet==4.2.1'.
root: Downloading https://files.pythonhosted.org/packages/ac/9d/608bd0ee93b23ba035f0338044fa7e8ecd0bde0679f2f6a5603afc270a25/zope.viewlet-4.2.1-py2.py3-none-any.whl#sha256=2b37893767393c7df8e718d69d1881c0f1872caafa15fbdaae08554ac566fd77
Got zope.viewlet 4.2.1.
root: Reading https://pypi.org/simple/zope.traversing/
Getting distribution for 'zope.traversing==4.4.1'.
root: Downloading https://files.pythonhosted.org/packages/9c/a4/3312e91ecd12a0878b8e36b690efabcee509e7ff9728bd3242ef56755659/zope.traversing-4.4.1-py2.py3-none-any.whl#sha256=1c05453726f574870121ccac90182b0ffc570b36dab5c60b9457369dd2018d34
Got zope.traversing 4.4.1.
root: Reading https://pypi.org/simple/zope.testing/
Getting distribution for 'zope.testing==4.7'.
root: Downloading https://files.pythonhosted.org/packages/14/d3/7849b49ab07065cb30380ad9a0bf4ea87ecd8cc456be95d32a5c4d8a6389/zope.testing-4.7-py2.py3-none-any.whl#sha256=32a9613fc8ed8f4992a854d1a05412615695bc90632c7aa858e9988b3827ee19
Got zope.testing 4.7.
root: Reading https://pypi.org/simple/zope.testbrowser/
Getting distribution for 'zope.testbrowser==5.5.1'.
root: Downloading https://files.pythonhosted.org/packages/e8/f9/e2a527c50b35166354abffb3e15aec32d83e56fdb2d9af9fe4f3dbc0110a/zope.testbrowser-5.5.1-py2.py3-none-any.whl#sha256=1c2ca8d89b52b545fc1de5e01a37df1c5901f28cc205cbd149f56346293d7d52
While:
  Installing zopescripts.
  Getting distribution for 'zope.testbrowser==5.5.1'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3109, in _dep_map
    return self.__dep_map
           ^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2902, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 35, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/_parser.py", line 210, in _parse_specifier
    with tokenizer.enclosing_tokens(
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 187, in enclosing_tokens
    self.raise_syntax_error(
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/buildout.py", line 2252, in main
    getattr(buildout, command)(args)
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/buildout.py", line 856, in install
    installed_files = self[part]._call(recipe.install)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/buildout.py", line 1652, in _call
    return f()
           ^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/zc.recipe.egg-2.0.7-py3.11-macosx-13-arm64.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
               ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/zc.recipe.egg-2.0.7-py3.11-macosx-13-arm64.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
         ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/eggs/zc.recipe.egg-2.0.7-py3.11-macosx-13-arm64.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/easy_install.py", line 971, in install
    return installer.install(specs, working_set)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/easy_install.py", line 744, in install
    for dist in self._get_dist(req, ws):
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/easy_install.py", line 581, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/easy_install.py", line 1913, in _move_to_eggs_dir_and_compile
    unpacker(dist.location, tmp_dest)
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/zc/buildout/easy_install.py", line 1847, in unpack_wheel
    wheel.install_as_egg(os.path.join(dest, wheel.egg_name()))
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/setuptools/wheel.py", line 120, in install_as_egg
    self._install_as_egg(destination_eggdir, zf)
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/setuptools/wheel.py", line 128, in _install_as_egg
    self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/setuptools/wheel.py", line 164, in _convert_metadata
    install_requires = list(map(raw_req, dist.requires()))
                                         ^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2822, in requires
    dm = self._dep_map
         ^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3111, in _dep_map
    self.__dep_map = self._compute_dependencies()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3121, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3174, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Volumes/Scotty/sandbox/Zope-5.8.4/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
    pytz (>dev)
         ~^

sfl@defiant Zope-5.8.4 % 
```

**Comment by dataflake** [comment]
The documentation says "The following examples are from Linux and use Zope version 5.0. Just replace that version number with your desired version." - your buildout configuration points to a versions configuration for Zope 5.0. Fix that first.

**Comment by sfluehnsdorf** [comment]
Ouch! Sorry, that was really stupid of me.

It worked perfectly with the correct version in the buildout configuration, including Zope startup
