### ISSUE TITLE
    from zope.pagetemplate.pagetemplate import _error_start, PTRuntimeError ImportError: cannot import name _error_start

### ISSUE THREAD

**Issue by chisangad** [zopefoundation/Zope#14]
I quiet new to Zope and I have been trying to install Zope 2.13.22 on a windows machine with Python 2.7 following the instructions; http://docs.zope.org/zope2/releases/2.13/INSTALL.html, I followed them religiously, managed to the create the virtual environment and installed Zope to the virtual environment, I then created an instance of Zope, but my trouble is each time  I try to run zope using the zopectl fg, I get the error below; 

Traceback (most recent call last):
  File "D:\ZopeEnv2\Scripts\runzope-script.py", line 9, in <module>
    load_entry_point('zope2==2.13.22', 'console_scripts', 'runzope')()
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Zope2\Startup\run
py", line 22, in run
    starter.prepare()
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Zope2\Startup__i
it__.py", line 86, in prepare
    self.startZope()
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Zope2\Startup__i
it__.py", line 262, in startZope
    Zope2.startup()
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Zope2__init__.py
, line 46, in startup
    from Zope2.App.startup import startup as _startup
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Zope2\App\startup
py", line 38, in <module>
    import OFS.Application
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\OFS\Application.p
", line 29, in <module>
    from App.ApplicationManager import ApplicationManager
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\App\ApplicationMa
ager.py", line 39, in <module>
    from Products.PageTemplates.PageTemplateFile import PageTemplateFile
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Products\PageTemp
ates\PageTemplateFile.py", line 30, in <module>
    from Products.PageTemplates.PageTemplate import PageTemplate
  File "D:\ZopeEnv2\lib\site-packages\zope2-2.13.22-py2.7.egg\Products\PageTemp
ates\PageTemplate.py", line 19, in <module>
    from zope.pagetemplate.pagetemplate import _error_start, PTRuntimeError
ImportError: cannot import name _error_start

I found a similar issue I found another similar here https://github.com/zopefoundation/zope.pagetemplate/issues/1 , I tried downgrading zope.pagetemplate to v3.5.2 from v4 as advised in the post but this just added more misery and received the following error;
"error in zope.pagetemplate setup command: Distribution contains no modules or p
ckages for namespace package 'zope'"

As I mentioned I am quiet new at this and will appreciate any help...
Thanks

**Comment by macagua** [comment]
Hi @tseaver 

I try your solution with python 2.7 for Plone 4

```
(python2.7)macagua@dacagua:~/proyectos/plone/$ easy_install -i http://download.zope.org/Zope2/index/2.13.22 Zope2
Searching for Zope2
Best match: Zope2 2.13.21
Processing Zope2-2.13.21-py2.7.egg
Zope2 2.13.21 is already the active version in easy-install.pth
Installing runzope script to /home/macagua/virtualenv/python2.7/bin
Installing zopectl script to /home/macagua/virtualenv/python2.7/bin
Installing zpasswd script to /home/macagua/virtualenv/python2.7/bin
Installing addzope2user script to /home/macagua/virtualenv/python2.7/bin
Installing mkzopeinstance script to /home/macagua/virtualenv/python2.7/bin

Using /home/macagua/virtualenv/python2.7/lib/python2.7/site-packages/Zope2-2.13.21-py2.7.egg
Processing dependencies for Zope2
Searching for mechanize>=0.2.0
Reading http://download.zope.org/Zope2/index/2.13.22/mechanize/
Best match: mechanize 0.2.5
Downloading https://pypi.python.org/packages/source/m/mechanize/mechanize-0.2.5.zip
Processing mechanize-0.2.5.zip
Writing /tmp/easy_install-ArSoZT/mechanize-0.2.5/setup.cfg
Running mechanize-0.2.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ArSoZT/mechanize-0.2.5/egg-dist-tmp-5VMdQ7
Adding mechanize 0.2.5 to easy-install.pth file

Installed /home/macagua/virtualenv/python2.7/lib/python2.7/site-packages/mechanize-0.2.5-py2.7.egg
Searching for zc.lockfile
Reading http://download.zope.org/Zope2/index/2.13.22/zc.lockfile/
Best match: zc.lockfile 1.0.2
Downloading https://pypi.python.org/packages/source/z/zc.lockfile/zc.lockfile-1.0.2.tar.gz
Processing zc.lockfile-1.0.2.tar.gz
Writing /tmp/easy_install-_U1uOb/zc.lockfile-1.0.2/setup.cfg
Running zc.lockfile-1.0.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_U1uOb/zc.lockfile-1.0.2/egg-dist-tmp-rUNFwH
Adding zc.lockfile 1.0.2 to easy-install.pth file

Installed /home/macagua/virtualenv/python2.7/lib/python2.7/site-packages/zc.lockfile-1.0.2-py2.7.egg
Finished processing dependencies for Zope2
```

Then I check the installation like:

```
(python2.7)macagua@dacagua:~/proyectos/plone/$ ls ~/virtualenv/python2.7/lib/python2.7/site-packages/ | grep pagetemplate
zope.pagetemplate-4.0.4-py2.7.egg
```

I trying to rerun my zeo client like:

```
(python2.7)macagua@dacagua:~/proyectos/plone/$ ./bin/client1 fg
2015-03-17 03:40:54 INFO ZServer HTTP server started at Tue Mar 17 03:40:54 2015
	Hostname: localhost
	Port: 8080
Traceback (most recent call last):
  File "/home/macagua/proyectos/plone/parts/client1/bin/interpreter", line 277, in <module>
    exec(compile(__file__f.read(), __file__, "exec"))
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 76, in <module>
    run()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py", line 22, in run
    starter.prepare()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 86, in prepare
    self.startZope()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py", line 262, in startZope
    Zope2.startup()
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py", line 46, in startup
    from Zope2.App.startup import startup as _startup
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py", line 38, in <module>
    import OFS.Application
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/OFS/Application.py", line 29, in <module>
    from App.ApplicationManager import ApplicationManager
  File "/home/macagua/.buildout/eggs/Zope2-2.13.22-py2.7.egg/App/ApplicationManager.py", line 39, in <module>
    from Products.PageTemplates.PageTemplateFile import PageTemplateFile
  File "/home/macagua/virtualenv/python2.7/lib/python2.7/site-packages/Zope2-2.13.21-py2.7.egg/Products/PageTemplates/PageTemplateFile.py", line 30, in <module>
    from Products.PageTemplates.PageTemplate import PageTemplate
  File "/home/macagua/virtualenv/python2.7/lib/python2.7/site-packages/Zope2-2.13.21-py2.7.egg/Products/PageTemplates/PageTemplate.py", line 19, in <module>
    from zope.pagetemplate.pagetemplate import _error_start, PTRuntimeError
ImportError: cannot import name _error_start
```

Any idea?

**Comment by tseaver** [comment]
`zope.pagetemplate 4.0.4` was probably already installed. You need to remove the 'zope.pagetemplate-4.0.4.egg` from `site-packages` and re-run the `easy_install` command.

**Comment by macagua** [comment]
@tseaver it was fixed as you said me, now running my Zeo client, thanks!
