### ISSUE TITLE
'mkzopeinstance' is b0rken on Python3

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/Zope#145]
```bash
$ /opt/Python-3.6.0/bin/virtualenv /tmp/z2py36
...
$ cd /tmp/z2py36
$ bin/pip install -U setuptools pip wheel
...
$ bin/pip install -r http://zopefoundation.github.io/Zope/releases/4.0a6/requirements-full.txt
...
$ bin/mkzopeinstance -d var -u $LOGIN:$PASSWORD
Traceback (most recent call last):
  File "bin/mkzopeinstance", line 7, in <module>
    from ZServer.Zope2.utilities.mkzopeinstance import main
  File "/tmp/z2py36/lib/python3.6/site-packages/ZServer/__init__.py", line 71, in <module>
    utils.patchSyslogServiceName()
  File "/tmp/z2py36/lib/python3.6/site-packages/ZServer/utils.py", line 72, in patchSyslogServiceName
    from medusa import logger
ModuleNotFoundError: No module named 'medusa'
```

**Comment by tseaver** [comment]
Looks like `mkwsgiinstance` is the [preferred alternative](https://zope.readthedocs.io/en/latest/INSTALL-virtualenv.html).

**Comment by hannosch** [comment]
Yeah. The mkzopeinstance script is now provided by the ZServer project, which isn't Python 3 compatible. The Zope project provides the mkwsgiinstance script, which is Py3 compatible.

I've tried to document that a bit over at https://zope.readthedocs.io/en/latest/WHATSNEW.html. Improvements to that document are more than welcome :)

**Comment by tseaver** [comment]
I'm going to claim that 65a2bed fixes this issue.
