### ISSUE TITLE
multipart post requests fail in 4.0b2 on python3

### ISSUE THREAD

**Issue by bogi788** [zopefoundation/Zope#204]
Submitting multipart forms using POST requests sometimes causes following exception on Python 3.6.3:

```Traceback (most recent call last):
  File "/opt/zope-4.0b2/lib/python3.6/site-packages/ZPublisher/WSGIPublisher.py", line 127, in transaction_pubevents
    yield
  File "/opt/zope-4.0b2/lib/python3.6/site-packages/ZPublisher/WSGIPublisher.py", line 251, in publish_module
    response = _publish(request, new_mod_info)
  File "/opt/zope-4.0b2/lib/python3.6/site-packages/ZPublisher/WSGIPublisher.py", line 176, in publish
    request.processInputs()
  File "/opt/zope-4.0b2/lib/python3.6/site-packages/ZPublisher/HTTPRequest.py", line 514, in processInputs
    fs = ZopeFieldStorage(fp=fp, environ=environ, keep_blank_values=1)
  File "/opt/lib/python3.6/cgi.py", line 559, in __init__
    self.read_multi(environ, keep_blank_values, strict_parsing)
  File "/opt/lib/python3.6/cgi.py", line 730, in read_multi
    self.encoding, self.errors)
  File "/opt/lib/python3.6/cgi.py", line 561, in __init__
    self.read_single()
  File "/opt/lib/python3.6/cgi.py", line 743, in read_single
    self.read_lines()
  File "/opt/lib/python3.6/cgi.py", line 772, in read_lines
    self.read_lines_to_outerboundary()
  File "/opt/lib/python3.6/cgi.py", line 848, in read_lines_to_outerboundary
    self.__write(odelim + line)
  File "/opt/lib/python3.6/cgi.py", line 782, in __write
    self.file.write(data)
  File "/opt/lib/python3.6/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by bogi788** [comment]
I've had some more time to look into this, and i'm fairly certain the problem is ZopeFieldStorage overriding the make_file method without checking the _binary_file attribute.

**Comment by tseaver** [comment]
@bogi788 Thanks for doing the digging!  If you comment out `ZopeFieldStorage.make_file` in your code, does everything work as you expect?

**Comment by bogi788** [comment]
Yes, everything seems to work as it is supposed to without make_file (or with adding the if as in FieldStorage.make_file).

**Comment by tseaver** [comment]
@hannosch Maybe we can just delete the `ZopeFieldStorage` altogether?  Or is it working around a 2.7 issue?  It has no tests, and its only purpose is to override `make_file` in a way which triggers this issue on 3.x.

**Comment by hannosch** [comment]
@tseaver IIRC it was introduced as part of optimizing file uploads, which would directly end up as blobs. And in particular work around an issue, which only happened on Windows around when tempfiles would be closed and whether or not those were still accessible to be moved/copied.

I think the idea was to make sure an uploaded file could be moved directly into the blobstorage directory without copying it, if the temp directory and blobstorage resided on the same partition.

But that's all from memory, so maybe I'm wrong. There's no tests for blob storage handling in Zope and none of the built-in types use blobs.

This is basically an upstreamed patch from plone.app.blob (https://github.com/plone/plone.app.blob/blob/1.6.x/src/plone/app/blob/monkey.py).

**Comment by tseaver** [comment]
#233 just removes `ZopeFieldStorage`, leaving behind a BBB alias to `cgi.FieldStorage`.
