### ISSUE TITLE
Submitting larger text-content with form.enctype=multipart/form-data: TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by zmsdev** [zopefoundation/Zope#223]
Page-Template content for reproduction of error:

```html
<!DOCTYPE html>
<html lang="en">
<body>
<form class="form-horizontal" action="#" method="post" enctype="multipart/form-data">
<textarea class="form-control input-sm interface" name="attr_custom_interface0">
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
         1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
</textarea>
<button type="submit" name="btn" class="btn btn-primary" value="Speichern">Speichern</button>
</form>
</body>
</html>
```

I get the following error, when I view the Page Template and try to submit the textarea (see below).
If the texteara contains less content, e.g. 'xyz' the form can be submitted without any problem:

```
2017-11-15 20:31:42 - ERROR [waitress] Exception when serving /myzmsx/content/metaobj_manager/manage_changeProperties
Traceback (most recent call last):
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/waitress-1.1.0-py3.4.egg/waitress/channel.py", line 338, in service
    task.service()
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/waitress-1.1.0-py3.4.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/waitress-1.1.0-py3.4.egg/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/Zope-4.0b2-py3.4.egg/ZPublisher/httpexceptions.py", line 33, in __call__
    return self.application(environ, start_response)
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/Zope-4.0b2-py3.4.egg/ZPublisher/WSGIPublisher.py", line 251, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/Zope-4.0b2-py3.4.egg/ZPublisher/WSGIPublisher.py", line 176, in publish
    request.processInputs()
  File "/home/zope4b1/virtualpy3/lib/python3.4/site-packages/Zope-4.0b2-py3.4.egg/ZPublisher/HTTPRequest.py", line 514, in processInputs
    fs = ZopeFieldStorage(fp=fp, environ=environ, keep_blank_values=1)
  File "/usr/lib/python3.4/cgi.py", line 559, in __init__
    self.read_multi(environ, keep_blank_values, strict_parsing)
  File "/usr/lib/python3.4/cgi.py", line 714, in read_multi
    self.encoding, self.errors)
  File "/usr/lib/python3.4/cgi.py", line 561, in __init__
    self.read_single()
  File "/usr/lib/python3.4/cgi.py", line 727, in read_single
    self.read_lines()
  File "/usr/lib/python3.4/cgi.py", line 756, in read_lines
    self.read_lines_to_outerboundary()
  File "/usr/lib/python3.4/cgi.py", line 832, in read_lines_to_outerboundary
    self.__write(odelim + line)
  File "/usr/lib/python3.4/cgi.py", line 766, in __write
    self.file.write(data)
  File "/usr/lib/python3.4/tempfile.py", line 538, in func_wrapper
    return func(*args, **kwargs)
TypeError: 'str' does not support the buffer interface
```

Of course I could use form.enctype=In this simple example I could use application/x-www-form-urlencoded but the example should just demonstrate the failure. In the moment I can not submit forms with textarea- and input.file-elements with Zope4.
Any help appreciated.

**Comment by dwt** [comment]
I can reproduce this problem with zope4-beta2 with python3.6, while it works with python2. (Which is to be expected as the bug smells like a python3 regression).

**Comment by dwt** [comment]
This workaround seems to fix this issue for me:

```diff
diff --git a/src/ZPublisher/HTTPRequest.py b/src/ZPublisher/HTTPRequest.py
index d3ed98da5..cb27861fa 100644
--- a/src/ZPublisher/HTTPRequest.py
+++ b/src/ZPublisher/HTTPRequest.py
@@ -1665,10 +1665,13 @@ class TemporaryFileWrapper(_TemporaryFileWrapper):
 
 
 class ZopeFieldStorage(FieldStorage):
-
-    def make_file(self, binary=None):
-        handle, name = mkstemp()
-        return TemporaryFileWrapper(os.fdopen(handle, 'w+b'), name)
+    
+    # on py3 it is important to open the file in binary mode only if it is a binary field. 
+    # Since all the wrappers don't do anything on py3 anyway, we're just leaving it out
+    if PY2:
+        def make_file(self, binary=None):
+            handle, name = mkstemp()
+            return TemporaryFileWrapper(os.fdopen(handle, 'w+b'), name)
 
 # Original version: zope.publisher.browser.FileUpload
 class FileUpload(object):
```

Still working on a test.

**Comment by tseaver** [comment]
I think we can just scrap `ZopeFieldStorage` altogether, leaving behind a BBB alias to `cgi.Fieldstorage`.

**Comment by tseaver** [comment]
@zmsdev Can you try to reproduce with the branch in #233?

**Comment by zmsdev** [comment]
Thanks to all, #233 works perfectly fine and solves the problem for me!

**Comment by dwt** [comment]
@tseaver: I was about to make a pull request - do you want to add the test I added to have better coverage for this in the future? (Not sure it matters if completely dropping the ZopeFieldStorage is the solution though)

Adding it here for posterity:

```diff
diff --git a/src/ZPublisher/HTTPRequest.py b/src/ZPublisher/HTTPRequest.py
index d3ed98da5..cb27861fa 100644
--- a/src/ZPublisher/HTTPRequest.py
+++ b/src/ZPublisher/HTTPRequest.py
@@ -1665,10 +1665,13 @@ class TemporaryFileWrapper(_TemporaryFileWrapper):
 
 
 class ZopeFieldStorage(FieldStorage):
-
-    def make_file(self, binary=None):
-        handle, name = mkstemp()
-        return TemporaryFileWrapper(os.fdopen(handle, 'w+b'), name)
+    
+    # on py3 it is important to open the file in binary mode only if it is a binary field. 
+    # Since all the wrappers don't do anything on py3 anyway, we're just leaving it out
+    if PY2:
+        def make_file(self, binary=None):
+            handle, name = mkstemp()
+            return TemporaryFileWrapper(os.fdopen(handle, 'w+b'), name)
 
 # Original version: zope.publisher.browser.FileUpload
 class FileUpload(object):
diff --git a/src/ZPublisher/tests/testHTTPRequest.py b/src/ZPublisher/tests/testHTTPRequest.py
index ccf5c187b..a7e4cfd84 100644
--- a/src/ZPublisher/tests/testHTTPRequest.py
+++ b/src/ZPublisher/tests/testHTTPRequest.py
@@ -816,6 +816,15 @@ class HTTPRequestTests(unittest.TestCase, HTTPRequestFactoryMixin):
         f = req.form.get('largefile')
         self.assertTrue(f.name)
         self.assertEqual(4006, len(f.file.read()))
+    
+    def test_processInputs_with_large_inputs_doesnt_explode_tempfile(self):
+        # check tempfile generation handles binary inputs correctly
+        s = BytesIO(TEST_LARGE_FIELD_DATA)
+        
+        environ = self._makePostEnviron(body=TEST_LARGE_FIELD_DATA)
+        req = self._makeOne(stdin=s, environ=environ)
+        req.processInputs()
+        # should not have exploded
 
     def test_processInputs_with_file_upload_gets_iterator(self):
         # checks fileupload object supports the iterator protocol
@@ -1221,3 +1230,17 @@ Content-Disposition: form-data; name="largefile"; filename="largefile"
 Content-Type: application/octet-stream
 
 test ''' + (b'test' * 1000) + b'\n\n'
+
+TEST_LARGE_FIELD_DATA = b'''--12345
+Content-Disposition: form-data; name="big_field"
+
+''' + b'''\
+         1         2         3         4         5         6         7         8
+12345678901234567890123456789012345678901234567890123456789012345678901234567890''' * 8 + b'''
+
+--12345
+Content-Disposition: form-data; name="btn"
+
+Speichern
+--12345--
+'''
```
