### ISSUE TITLE
ZMI: items are strangely ordered

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#248]
I saw the following behaviour in the listen view (`manage_main`) of a `Folder` (_not_ the ordered one) in the ZMI of Zope 4:

When renaming an object it is sorted to the end of the list.

Expected behaviour: sort the list by the ids of the items (the links to sort the list in the browser do not exist any more.)

**Comment by sallner** [comment]
The sorting was most certainly removed during the feature reduction for Zope 4. In https://github.com/zopefoundation/Zope/blob/2.13/src/OFS/dtml/main.dtml#L121 the respective sorting can be seen in the dtml. 

But as https://github.com/zopefoundation/Zope/pull/249 is actually changing the template to ZPT and `tal:repeat` does not support sorting like `dtml-in` we should find a appropriate solution at the point of merge there.

**Comment by viktordick** [comment]
The original behavior can not be reproduced, if I rename an object, it is sorted correctly.

There is still a difference in the sorting: In Zope 2.13, objects with IDs that start with a capital letter were sorted to the beginning, this is no longer the case.

**Comment by viktordick** [comment]
Related problem: if broken objects are part of the currently shown folder, the sorting code (in Products.sequencesort) breaks:

    2018-10-01 17:30:26 - ERROR [waitress] Exception when serving /manage_main
    Traceback (most recent call last):
      File "/home/vdick/Zope4/lib/python3.6/site-packages/chameleon/template.py", line 183, in render
        self._render(stream, econtext, rcontext)
      File "8b7ffd8f82cb13cc5f45f0fa20d13391.py", line 225, in render
      File "/home/vdick/Zope4/lib/python3.6/site-packages/zope/sequencesort/ssort.py", line 154, in sort
        s.sort(key=cmp_to_key(by))
      File "/home/vdick/Zope4/lib/python3.6/site-packages/zope/sequencesort/ssort.py", line 272, in __call__
        n = func(c1, c2)
    TypeError: strcoll() argument 1 must be str, not _Smallest
