### ISSUE TITLE
Database errors when running Zope behind uwsgi with multiple workers

### ISSUE THREAD

**Issue by tschorr** [zopefoundation/Zope#283]
`uwsgi.ini` contents:

```
[uwsgi]
http-socket = 0.0.0.0:8080
socket = 127.0.0.1:8081
chdir  = /home/thomas/devel/buildout.coredev/bin
module = wsgi:application
master = true
processes = 2
```

Command line is `uwsgi --ini uwsgi.ini`.

When trying to access the ZMI, I see:

```
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 5369)
spawned uWSGI worker 1 (pid: 5382, cores: 1)
spawned uWSGI worker 2 (pid: 5383, cores: 1)
[pid: 5383|app: 0|req: 1/1] 127.0.0.1 () {36 vars in 653 bytes} [Fri May 18 08:55:09 2018] GET /manage => generated 561 bytes in 22 msecs (HTTP/1.1 200) 6 headers in 227 bytes (2 switches on core 0)
ERROR:ZODB.serialize:Unpickling error: b'\x80\x03cProducts.PlonePAS.tools.memberdata\nMemberDataTool\nq\x00.\x80\x03}q\x01(X\x08\x00\x00\x00_membersq\x02C\x08\x00\x00\x00\x00\x00\x00\n\xceq\x03cBTrees.OOBTree\nOOBTree\nq\x04\x86q\x05QX\t\x00\x00\x00portraitsq\x06C\x08\x00\x00\x00\x00\x00\x00\n\xcfq\x07cProducts.BTreeFolder2.BTreeFolder2\nBTreeFolder2\nq\x08\x86q\tQX\x12\x00\x00\x00__ac_local_roles__q\n}q\x0bX\x05\x00\x00\x00adminq\x0c]\x00\x00_objectsq\x02(}q\x03(X\x02\x00\x00\x00idq\x04X\x0f\x00\x00\x00virtual_hostingq\x05X\t\x00\x00\x00meta_typeq\x06X\x14\x00\x00\x00Virtual Host Monsterq\x07u}q\x08(h\x04X\n\x00\x00\x00index_htmlq\th\x06X\r\x00\x00\x00Page Templateq\nu}q\x0b(h\x04X\x05\x00\x00\x00Ploneq\x0ch\x06X\n\x00\x00\x00Plone Siteq\ru}q\x0e(h\x04X\t\x00\x00\x00acl_usersq\x0fh\x06X\x16\x00\x00\x00Pluggable Auth Serviceq\x10utq\x11h\x05C\x08\x00\x00\x00\x00\x00\x00\x00\x05q\x12cProducts.SiteAccess.VirtualHostMonster\nVirtualHostMonster\nq\x13\x86q\x14QX\x13\x00\x00\x00__before_traverse__q\x15}q\x16(K\x19h\x07\x86q\x17cZPublisher.BeforeTraverse\nNameCaller\nq\x18)\x81q\x19}q\x1aX\x04\x00\x00\x00nameq\x1bh\x05sbKcX \x00\x00\x00Pluggable Auth Service/acl_usersq\x1c\x86q\x1dh\x18)\x81q\x1e}q\x1fh\x1bh\x0fsbuX\x1e\x00\x00\x00__before_publishing_traverse__q cZPublisher.BeforeTraverse\nMultiHook\nq!)\x81q"}q#(X\t\x00\x00\x00_hooknameq$h X\x06\x00\x00\x00_priorq%NX\x11\x00\x00\x00_defined_in_classq&\x89X\x05\x00\x00\x00_listq\']q((h\x19h\x1eeubh\tC\x08\x00\x00\x00\x00\x00\x00\x00\x06q)cProducts.PageTemplates.ZopePageTemplate\nZopePageTemplate\nq*\x86q+QX\x0c\x00\x00\x00_key_managerq,cplone.keyring.keymanager\nKeyManager\nq-)\x81q.}q/X\x16\x00\x00\x00_SampleContainer__dataq0C\x08\x00\x00\x00\x00\x00\x00\x00\x07q1cpersistent.mapping\nPersistentMapping\nq2\x86q3QsbX\x05\x00\x00\x00Ploneq4C\x08\x00\x00\x00\x00\x00\x00\x00\x0bq5cProduct'
Traceback (most recent call last):
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
EOFError
ERROR:ZODB.Connection:Couldn't load state for Products.PlonePAS.tools.memberdata.MemberDataTool 0x26
Traceback (most recent call last):
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
EOFError
Traceback (most recent call last):
  File "./wsgi.py", line 245, in application
    def application(*args, **kwargs):return wsgiapp(*args, **kwargs)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 270, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 210, in publish
    bind=1)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 57, in call_object
    return obj(*args)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/Shared/DC/Scripts/Bindings.py", line 330, in __call__
    return self._bindAndExec(args, kw, None)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/Shared/DC/Scripts/Bindings.py", line 367, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/App/special_dtml.py", line 203, in _exec
    result = render_blocks(self._v_blocks, ns)
  File "/home/thomas/devel/plone/buildout.coredev/src/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 147, in render_blocks
    render_blocks_(blocks, rendered, md)
  File "/home/thomas/devel/plone/buildout.coredev/src/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 248, in render_blocks_
    block = block(md)
  File "/home/thomas/devel/plone/buildout.coredev/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 115, in render
    return tpRender(v, md, self.section, self.args)
  File "/home/thomas/devel/plone/buildout.coredev/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 247, in tpRender
    section, md, treeData, level, args)
  File "/home/thomas/devel/plone/buildout.coredev/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 519, in tpRenderTABLE
    colspan, section, md, treeData, level, args)
  File "/home/thomas/devel/plone/buildout.coredev/src/DocumentTemplate/src/TreeDisplay/TreeTag.py", line 301, in tpRenderTABLE
    items = items()
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/OFS/OrderSupport.py", line 259, in tpValues
    r = [obj for obj in self.objectValues()
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/OFS/OrderSupport.py", line 260, in <listcomp>
    if getattr(obj, 'isPrincipiaFolderish', False)]
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
EOFError
```

**Comment by tschorr** [comment]
when trying to access a Plone site contained in the DB, I also see:

```
Traceback (most recent call last):
  File "./wsgi.py", line 245, in application
Traceback (most recent call last):
  File "./wsgi.py", line 245, in application
    def application(*args, **kwargs):return wsgiapp(*args, **kwargs)
    def application(*args, **kwargs):return wsgiapp(*args, **kwargs)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 270, in publish_module
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 270, in publish_module
    response = _publish(request, new_mod_info)
    response = _publish(request, new_mod_info)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 198, in publish
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 198, in publish
    obj = request.traverse(path, validated_hook=validate_user)
    obj = request.traverse(path, validated_hook=validate_user)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 524, in traverse
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 524, in traverse
    subobject = self.traverseName(object, entry_name)
    subobject = self.traverseName(object, entry_name)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 353, in traverseName
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 353, in traverseName
    ob2 = adapter.publishTraverse(self, name)
    ob2 = adapter.publishTraverse(self, name)
  File "/home/thomas/devel/plone/buildout.coredev/src/Products.CMFPlone/Products/CMFPlone/browser/admin.py", line 49, in publishTraverse
  File "/home/thomas/devel/plone/buildout.coredev/src/Products.CMFPlone/Products/CMFPlone/browser/admin.py", line 49, in publishTraverse
    return DefaultPublishTraverse.publishTraverse(self, request, name)
    return DefaultPublishTraverse.publishTraverse(self, request, name)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 110, in publishTraverse
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 110, in publishTraverse
    raise e
    raise e
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 87, in publishTraverse
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 87, in publishTraverse
    subobject = object.__bobo_traverse__(request, name)
    subobject = object.__bobo_traverse__(request, name)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/OFS/Application.py", line 137, in __bobo_traverse__
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/OFS/Application.py", line 137, in __bobo_traverse__
    REQUEST.RESPONSE.notFoundError("%s\n%s" % (name, method))
    REQUEST.RESPONSE.notFoundError("%s\n%s" % (name, method))
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/HTTPResponse.py", line 1006, in notFoundError
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/HTTPResponse.py", line 1006, in notFoundError
    raise exc
    raise exc
zExceptions.NotFound: favicon.ico
```

and

```
[pid: 5382|app: 0|req: 18/36] 127.0.0.1 () {36 vars in 768 bytes} [Fri May 18 08:55:23 2018] GET /Plone/++plone++static/++unique++2018-05-17%2017%3A44%3A44.422577/plone-legacy-compiled.js => generated 13681 bytes in 10 msecs (HTTP/1.1 200) 7 headers in 276 bytes (2 switches on core 0)
Traceback (most recent call last):
  File "./wsgi.py", line 245, in application
    def application(*args, **kwargs):return wsgiapp(*args, **kwargs)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 270, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 210, in publish
    bind=1)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 57, in call_object
    return obj(*args)
  File "/home/thomas/devel/plone/buildout.coredev/src/Products.CMFPlone/Products/CMFPlone/resources/browser/configjs.py", line 89, in __call__
    (paths, shims) = self.get_requirejs_config()
  File "/home/thomas/devel/plone/buildout.coredev/src/Products.CMFPlone/Products/CMFPlone/resources/browser/configjs.py", line 63, in get_requirejs_config
    if script.js:
  File "/home/thomas/.buildout/eggs/cp36m/plone.registry-1.1.2-py3.6.egg/plone/registry/recordsproxy.py", line 50, in __getattr__
    value = self.__registry__.get(self.__prefix__ + name, _marker)
  File "/home/thomas/.buildout/eggs/cp36m/plone.registry-1.1.2-py3.6.egg/plone/registry/registry.py", line 47, in get
    return self.records._values.get(name, default)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
_pickle.UnpicklingError: invalid load key, ','.
```

**Comment by tschorr** [comment]
Using only one process but multiple threads seems to work:

```
[uwsgi]
http-socket = 0.0.0.0:8080
socket = 127.0.0.1:8081
chdir  = /home/thomas/devel/plone/buildout.coredev/bin
module = wsgi:application
master = true
enable-threads = true
processes = 1
threads = 2
```

**Comment by tschorr** [comment]
Like in #284 using `master = false` seems to resolve the issue when using a single process and either threads or asyncio workers.

When using multiple processes, I still get:

```
Traceback (most recent call last):
  File "./wsgi.py", line 245, in application
    def application(*args, **kwargs):return wsgiapp(*args, **kwargs)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 270, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/WSGIPublisher.py", line 198, in publish
    obj = request.traverse(path, validated_hook=validate_user)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BaseRequest.py", line 457, in traverse
    bpth(object, self)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BeforeTraverse.py", line 109, in __call__
    cob(container, request)
  File "/home/thomas/devel/plone/buildout.coredev/src/Zope/src/ZPublisher/BeforeTraverse.py", line 146, in __call__
    args = getattr(getattr(aq_base(meth), '__code__', None),
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/Connection.py", line 791, in setstate
    p, serial = self._storage.load(oid)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/mvccadapter.py", line 143, in load
    r = self._storage.loadBefore(oid, self._start)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/FileStorage/FileStorage.py", line 567, in loadBefore
    h = self._read_data_header(pos, oid, _file)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/FileStorage/format.py", line 150, in _read_data_header
    h = DataHeaderFromString(s)
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/FileStorage/format.py", line 236, in DataHeaderFromString
    return DataHeader(*struct.unpack(DATA_HDR, s))
  File "/home/thomas/.buildout/eggs/cp36m/ZODB-5.4.0-py3.6.egg/ZODB/FileStorage/format.py", line 246, in __init__
    "Non-zero version length. Versions aren't supported.")
ValueError: Non-zero version length. Versions aren't supported.
```
