### ISSUE TITLE
TreeTagDisplay explodes when viewing Products.CMFCore.DirectoryView

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Zope#332]
To reproduce

1. Install Products.CMFCore
2. Instantiate FilesystemDirectoryView in the root folder of the zodb
3. switch to the two frame display and watch the left frame explode

The traceback looks like this for me:

```
2018-10-01 18:58:00 - ERROR [Zope.SiteErrorLog] 1538413080.64545580.2069454659404485 http://localhost:8080/manage_menu
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 128, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 270, in publish_module
  Module ZPublisher.WSGIPublisher, line 210, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 57, in call_object
  Module Shared.DC.Scripts.Bindings, line 330, in __call__
  Module Shared.DC.Scripts.Bindings, line 367, in _bindAndExec
  Module App.special_dtml, line 203, in _exec
  Module DocumentTemplate._DocumentTemplate, line 147, in render_blocks
  Module DocumentTemplate._DocumentTemplate, line 248, in render_blocks_
  Module TreeDisplay.TreeTag, line 115, in render
  Module TreeDisplay.TreeTag, line 247, in tpRender
  Module TreeDisplay.TreeTag, line 508, in tpRenderTABLE
   - __traceback_info__: (['AAAAAAAAAAE='], {'nowrap': '1', 'branches': 'tpValues', 'id': 'tpId', 'url': 'tpURL', 'childless_decoration': ''}, [['AAAAAAAAAAE=']], [['AAAAAAAAAAE=']])
  Module TreeDisplay.TreeTag, line 751, in oid
TypeError: a bytes-like object is required, not 'NoneType'
2018-10-01 18:58:00 - ERROR [waitress] Exception when serving /manage_menu
Traceback (most recent call last):
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/waitress/channel.py", line 338, in service
    task.service()
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 270, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 210, in publish
    bind=1)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 57, in call_object
    return obj(*args)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/Shared/DC/Scripts/Bindings.py", line 330, in __call__
    return self._bindAndExec(args, kw, None)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/Shared/DC/Scripts/Bindings.py", line 367, in _bindAndExec
    return self._exec(bound_data, args, kw)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/App/special_dtml.py", line 203, in _exec
    result = render_blocks(self._v_blocks, ns)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/DocumentTemplate/_DocumentTemplate.py", line 147, in render_blocks
    render_blocks_(blocks, rendered, md)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/DocumentTemplate/_DocumentTemplate.py", line 248, in render_blocks_
    block = block(md)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/TreeDisplay/TreeTag.py", line 115, in render
    return tpRender(v, md, self.section, self.args)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/TreeDisplay/TreeTag.py", line 247, in tpRender
    section, md, treeData, level, args)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/TreeDisplay/TreeTag.py", line 508, in tpRenderTABLE
    id = oid(item)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.6/site-packages/TreeDisplay/TreeTag.py", line 751, in oid
    value = b2a_base64(self._p_oid)[:-1]
TypeError: a bytes-like object is required, not 'NoneType'
```

I suspect that this TreeTag should be robust against this error condition - but maybe this is really an issue in Products.CMFCore

**Comment by dwt** [comment]
Actually, this should be on DocumentTemplate, moving it there.
