### ISSUE TITLE
mkwsgiinstance:  Fails under Py3k on Unix filesystem

### ISSUE THREAD

**Issue by tseaver** [zopefoundation/Zope#372]
In a fresh Zope 4.0b6 install:

```bash
$ bin/mkwsgiinstance -d .
Please choose a username and password for the initial user.
These will be the credentials you use to initially manage
your new Zope instance.

Username: xxx
Password: 
Verify password: 
Traceback (most recent call last):
  File "bin/mkwsgiinstance", line 11, in <module>
    sys.exit(main())
  File "/tmp/zope4/lib/python3.6/site-packages/Zope2/utilities/mkwsgiinstance.py", line 142, in main
    copyzopeskel.copyskel(skelsrc, skeltarget, None, None, **kw)
  File "/tmp/zope4/lib/python3.6/site-packages/Zope2/utilities/copyzopeskel.py", line 182, in copyskel
    copydir(root, dirs, files, targetdir, replacements, uid, gid)
  File "/tmp/zope4/lib/python3.6/site-packages/Zope2/utilities/copyzopeskel.py", line 206, in copydir
    gid)
  File "/tmp/zope4/lib/python3.6/site-packages/Zope2/utilities/copyzopeskel.py", line 225, in copyin
    text = text.replace("<<%s>>" % k, replacements[k])
TypeError: replace() argument 2 must be str, not bytes
```

Debugging, the issue is that `ZOPE2PATH` is bytes.

**Comment by aodag** [comment]
FYI: on windows, I got same error.

```
(.venv) C:\Users\aodag\works\zope\Products.MyBlog> mkwsgiinstance.exe -d .
Please choose a username and password for the initial user.
These will be the credentials you use to initially manage
your new Zope instance.

Username: admin
Password:
Verify password:
Traceback (most recent call last):
  File "C:\Users\aodag\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\aodag\AppData\Local\Programs\Python\Python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\aodag\works\zope\Products.MyBlog\.venv\Scripts\mkwsgiinstance.exe\__main__.py", line 9, in <module>
  File "c:\users\aodag\works\zope\products.myblog\.venv\lib\site-packages\Zope2\utilities\mkwsgiinstance.py", line 142, in main
    copyzopeskel.copyskel(skelsrc, skeltarget, None, None, **kw)
  File "c:\users\aodag\works\zope\products.myblog\.venv\lib\site-packages\Zope2\utilities\copyzopeskel.py", line 182, in copyskel
    copydir(root, dirs, files, targetdir, replacements, uid, gid)
  File "c:\users\aodag\works\zope\products.myblog\.venv\lib\site-packages\Zope2\utilities\copyzopeskel.py", line 206, in copydir
    gid)
  File "c:\users\aodag\works\zope\products.myblog\.venv\lib\site-packages\Zope2\utilities\copyzopeskel.py", line 225, in copyin
    text = text.replace("<<%s>>" % k, replacements[k])
TypeError: replace() argument 2 must be str, not bytes```

**Comment by gandie** [comment]
I quick-fixed that by replacing the line:
`text = text.replace("<<%s>>" % k, replacements[k])`
with
`text = text.replace("<<%s>>" % k, str(replacements[k]))`
Got a working instance after that, hope this helps.
