### ISSUE TITLE
Improper handling with non-ascii characters in response.redirect() in Zope 4/Python 3

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#435]
Situation:
- user enters the name of form which is send as parameter `name:unicode` to Plone 5.2/Python 3
- the browser view receives the parameter as `str` and creates response.redirect to
  `self.context.absolute() + '/view' + name`. In my case this is `/Plone2/s3/view/ä` 
- the browser redirects to `/Plone2/s3/view/%E4`  and waitress throws this exception:

```
2018-12-18 11:37:44,424 ERROR [waitress:341][waitress] Exception when serving /Plone2/s3/view/ääää
Traceback (most recent call last):
  File "/home/ajung/src/xmldirector.connector/eggs/waitress-1.1.0-py3.7.egg/waitress/channel.py", line 338, in service
    task.service()
  File "/home/ajung/src/xmldirector.connector/eggs/waitress-1.1.0-py3.7.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/ajung/src/xmldirector.connector/eggs/waitress-1.1.0-py3.7.egg/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/ajung/src/xmldirector.connector/eggs/Zope-4.0b7-py3.7.egg/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/ajung/src/xmldirector.connector/eggs/Zope-4.0b7-py3.7.egg/ZPublisher/WSGIPublisher.py", line 251, in publish_module
    path_info = path_info.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 16: invalid continuation byte

```

My browser view can clearly deal with a request to `/Plone2/s3/view/ä`  - however something is going here with the unicode <-> utf8 conversion - either as part of the generation of the redirection URL and/or with improper `%e4` as part of the redirection URL.

**Comment by zopyx** [comment]
I think that the redirect() call generates an improper redirection URL here:

The correct redirection URL for `/Plone2/s3/view/ä` must be `/Plone2/s3/view/%C3%A4` but not `/Plone2/s3/view/%E4`.

**Comment by dataflake** [comment]
The `redirect` call does not seem to be the issue. It's how paths are handled in the WSGI publisher.

The combination of 6c15c7148c83db108c72043fb065b06bfbcf076a by @sallner and 707df7360b8b77286db0caa111dab28c3b2eb5e1 by @icemac ends up with a strange mixture. Under Python 3, it takes a unicode value, encodes it into latin1, and immediately decodes it using UTF-8. I think we can all agree that can't work.

What is the intent here?
