### ISSUE TITLE
ZPublisher expecting a stream iterator providing a valid length

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#447]
We have this IStreamIterator implementation

```
@implementer(IStreamIterator)
class connector_iterator():
    """ Iterator for pyfilesystem content """

    def __init__(self, handle, filename, mode='rb', streamsize=1 << 24):
        self.handle = handle
        self.fp = handle.open(filename, mode)
        self.filename = filename
        self.streamsize = streamsize

    def __iter__(self):
        return self

    def __next__(self):
        data = self.fp.read(self.streamsize)
        if not data:
            raise StopIteration
        return data

    next = __next__

    def seek(self, *args):
        pass

    def __len__(self):
        return self.handle.getsize(self.filename)

``` 

The stream iterator operates on top of `PyFilesystem`. Short version: some backends like some webdav servers do not provide a value for `getsize()` - so it is not always guaranteed that `len()` on the iterator is supposed to return a valid number which explains the traceback.

```
2019-01-02 12:58:44,062 ERROR [waitress:341][waitress] Exception when serving /Plone4/de/editorial-board/5b3510de-05f9-11e9-809e-0050563d0e5e/@@raw/xml/index.xml
Traceback (most recent call last):
  File "/home/ajung/sandboxes/onkopedia_buildout-plone5/eggs/waitress-1.1.0-py3.6.egg/waitress/channel.py", line 338, in service
    task.service()
  File "/home/ajung/sandboxes/onkopedia_buildout-plone5/eggs/waitress-1.1.0-py3.6.egg/waitress/task.py", line 169, in service
    self.execute()
  File "/home/ajung/sandboxes/onkopedia_buildout-plone5/eggs/waitress-1.1.0-py3.6.egg/waitress/task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/ajung/sandboxes/onkopedia_buildout-plone5/eggs/Zope-4.0b7-py3.6.egg/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/ajung/sandboxes/onkopedia_buildout-plone5/eggs/Zope-4.0b7-py3.6.egg/ZPublisher/WSGIPublisher.py", line 283, in publish_module
    status, headers = response.finalize()
  File "/home/ajung/sandboxes/onkopedia_buildout-plone5/eggs/Zope-4.0b7-py3.6.egg/ZPublisher/HTTPResponse.py", line 1072, in finalize
    self.setHeader('content-length', len(self.body))
TypeError: 'str' object cannot be interpreted as an integer

```

**Comment by dataflake** [comment]
@zopyx Have you looked at the suggestion from the previous comment or did you solve it some other way? Just wondering if this needs to stay open.

**Comment by dataflake** [comment]
There is no indication that this is a bug and there was no further feedback after asking twice. Closing.
