### ISSUE TITLE
Missing error handling in ZMI when viewing invalid dtml

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/Zope#491]
Reproduce:
- create new DTML file in ZMI
- enter some invalid DTML like the dtml-in mySequence example from here https://docs.zope.org/zope2/zope2book/DTML.html#dtml-tag-syntax
- save
- hit view button

**Output:**
Internal Server Error
The server encountered an unexpected internal server error
(generated by waitress)

**Traceback**
`2019-02-11 12:15:33 - ERROR [waitress] Exception when serving /dtml
Traceback (most recent call last):
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/waitress-1.2.1-py3.6.egg/waitress/channel.py", line 336, in service
    task.service()
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/waitress-1.2.1-py3.6.egg/waitress/task.py", line 175, in service
    self.execute()
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/waitress-1.2.1-py3.6.egg/waitress/task.py", line 452, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/src/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/src/ZPublisher/WSGIPublisher.py", line 278, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/src/ZPublisher/WSGIPublisher.py", line 212, in publish
    bind=1)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/src/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/src/ZPublisher/WSGIPublisher.py", line 56, in call_object
    return obj(*args)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/src/OFS/DTMLDocument.py", line 94, in __call__
    r = HTML.__call__(self, (client, bself), REQUEST, **kw)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/DocumentTemplate-3.0b5-py3.6.egg/DocumentTemplate/DT_String.py", line 519, in __call__
    result = render_blocks(self._v_blocks, md)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/DocumentTemplate-3.0b5-py3.6.egg/DocumentTemplate/_DocumentTemplate.py", line 148, in render_blocks
    render_blocks_(blocks, rendered, md)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/DocumentTemplate-3.0b5-py3.6.egg/DocumentTemplate/_DocumentTemplate.py", line 249, in render_blocks_
    block = block(md)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/DocumentTemplate-3.0b5-py3.6.egg/DocumentTemplate/DT_In.py", line 664, in renderwob
    sequence = md[name]
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/DocumentTemplate-3.0b5-py3.6.egg/DocumentTemplate/_DocumentTemplate.py", line 379, in __getitem__
    return self.getitem(name, call=1)
  File "/home/jugmac00/Projects/Zope-playfield/Zope-4.0b9/eggs/DocumentTemplate-3.0b5-py3.6.egg/DocumentTemplate/_DocumentTemplate.py", line 405, in getitem
    raise KeyError(key)
KeyError: 'mySequence'
`

On a side note - maybe that has nothing to do with ZMI, but about error handling of Zope itself.

**Comment by dataflake** [comment]
Yes, this has nothing to do with the ZMI.

https://github.com/zopefoundation/Zope/pull/495 will make this a little less painful for those who are upgrading and still have a `standard_error_message` in place. Other than that you have to register exception views to get something nicer.
