### ISSUE TITLE
Exception while handling exception 

### ISSUE THREAD

**Issue by dwt** [zopefoundation/Zope#603]
While inspecting a database converted from python 2 to python 3 I noticed this unusual error handling strategy from zope. If I parse that correctly, then an error happens while handling the exception, which triggers an exception which then fails trying to start the wsgi response.

For detailed logs see the collapsed section below.

<details>

```
2019-05-09 11:29:20 - ERROR [ZODB.Connection] Couldn't load state for Products.zms.zms.ZMS 0x16ad35
Traceback (most recent call last):
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
_pickle.UnpicklingError: invalid load key, ''.
2019-05-09 11:29:20 - ERROR [root] Exception while rendering an error message
Traceback (most recent call last):
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 154, in transaction_pubevents
    yield
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 317, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 239, in publish
    obj = request.traverse(path, validated_hook=validate_user)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 523, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 350, in traverseName
    ob2 = adapter.publishTraverse(self, name)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 107, in publishTraverse
    raise e
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 84, in publishTraverse
    subobject = object.__bobo_traverse__(request, name)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/OFS/Application.py", line 136, in __bobo_traverse__
    REQUEST.RESPONSE.notFoundError("%s\n%s" % (name, method))
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/HTTPResponse.py", line 986, in notFoundError
    raise exc
zExceptions.NotFound: manage_page_style.css
GET

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/OFS/SimpleItem.py", line 299, in raise_standardErrorMessage
    v = s(client, REQUEST, **kwargs)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/OFS/DTMLMethod.py", line 164, in __call__
    r = HTML.__call__(self, client, REQUEST, **kw)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/DT_String.py", line 528, in __call__
    encoding=encoding)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 144, in render_blocks
    render_blocks_(blocks, rendered, md, encoding)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 236, in render_blocks_
    render_blocks_(block, rendered, md, encoding)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 166, in render_blocks_
    t = md[t]
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 375, in __getitem__
    return self.getitem(name, call=1)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 399, in getitem
    return e()
TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response'
2019-05-09 11:29:20 - ERROR [ZODB.Connection] Couldn't load state for Products.zms.zms.ZMS 0x16ad35
Traceback (most recent call last):
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
_pickle.UnpicklingError: invalid load key, ''.
2019-05-09 11:29:20 - ERROR [Zope.SiteErrorLog] 1557394160.8621270.8707151413542893 http://localhost:8080/manage_page_style.css
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 154, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 317, in publish_module
  Module ZPublisher.WSGIPublisher, line 239, in publish
  Module ZPublisher.BaseRequest, line 523, in traverse
  Module ZPublisher.BaseRequest, line 350, in traverseName
  Module ZPublisher.BaseRequest, line 107, in publishTraverse
  Module ZPublisher.BaseRequest, line 84, in publishTraverse
  Module OFS.Application, line 136, in __bobo_traverse__
  Module ZPublisher.HTTPResponse, line 986, in notFoundError
zExceptions.NotFound: manage_page_style.css
GET
2019-05-09 11:29:20 - ERROR [Zope.SiteErrorLog] 1557394160.8634220.9288258244960149 http://localhost:8080/sites/asors/index_html
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 154, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 317, in publish_module
  Module ZPublisher.WSGIPublisher, line 251, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 60, in call_object
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.PythonScripts.PythonScript, line 330, in _exec
  Module script, line 5, in index_html
   - <PythonScript at /sites/asors/index_html>
   - Line 5
  Module AccessControl.ZopeGuards, line 104, in guarded_getitem
  Module AccessControl.ZopeGuards, line 214, in _check_list_access
  Module ZODB.Connection, line 795, in setstate
  Module ZODB.serialize, line 633, in setGhostState
  Module ZODB.serialize, line 626, in getState
_pickle.UnpicklingError: invalid load key, ''.
2019-05-09 11:29:20 - INFO  [wsgi] 127.0.0.1 - - [09/Mai/2019:11:29:20 +0200] "GET /manage_page_style.css HTTP/1.1" 404 276 "http://localhost:8080/sites/asors/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
2019-05-09 11:29:20 - INFO  [wsgi] 127.0.0.1 - - [09/Mai/2019:11:29:20 +0200] "GET /sites/asors/ HTTP/1.1" 500 923 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
2019-05-09 11:29:20 - ERROR [root] Exception while rendering an error message
Traceback (most recent call last):
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 154, in transaction_pubevents
    yield
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 317, in publish_module
    response = _publish(request, new_mod_info)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/WSGIPublisher.py", line 239, in publish
    obj = request.traverse(path, validated_hook=validate_user)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 523, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 350, in traverseName
    ob2 = adapter.publishTraverse(self, name)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 107, in publishTraverse
    raise e
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/BaseRequest.py", line 84, in publishTraverse
    subobject = object.__bobo_traverse__(request, name)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/OFS/Application.py", line 136, in __bobo_traverse__
    REQUEST.RESPONSE.notFoundError("%s\n%s" % (name, method))
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/ZPublisher/HTTPResponse.py", line 986, in notFoundError
    raise exc
zExceptions.NotFound: manage_page_style.css
GET

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/OFS/SimpleItem.py", line 299, in raise_standardErrorMessage
    v = s(client, REQUEST, **kwargs)
  File "/Users/dwt/Code/Projekte/zope4/Zope/src/OFS/DTMLMethod.py", line 164, in __call__
    r = HTML.__call__(self, client, REQUEST, **kw)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/DT_String.py", line 528, in __call__
    encoding=encoding)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 144, in render_blocks
    render_blocks_(blocks, rendered, md, encoding)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 236, in render_blocks_
    render_blocks_(block, rendered, md, encoding)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 166, in render_blocks_
    t = md[t]
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 375, in __getitem__
    return self.getitem(name, call=1)
  File "/Users/dwt/Code/Projekte/zope4/DocumentTemplate/src/DocumentTemplate/_DocumentTemplate.py", line 399, in getitem
    return e()
TypeError: __call__() missing 2 required positional arguments: 'environ' and 'start_response'
2019-05-09 11:29:20 - ERROR [Zope.SiteErrorLog] 1557394160.9041260.5503829021760542 http://localhost:8080/manage_page_style.css
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 154, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 317, in publish_module
  Module ZPublisher.WSGIPublisher, line 239, in publish
  Module ZPublisher.BaseRequest, line 523, in traverse
  Module ZPublisher.BaseRequest, line 350, in traverseName
  Module ZPublisher.BaseRequest, line 107, in publishTraverse
  Module ZPublisher.BaseRequest, line 84, in publishTraverse
  Module OFS.Application, line 136, in __bobo_traverse__
  Module ZPublisher.HTTPResponse, line 986, in notFoundError
zExceptions.NotFound: manage_page_style.css
GET
2019-05-09 11:29:20 - INFO  [wsgi] 127.0.0.1 - - [09/Mai/2019:11:29:20 +0200] "GET /manage_page_style.css HTTP/1.1" 404 276 "http://localhost:8080/sites/asors/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1 Safari/605.1.15"
```

</details>

**Comment by dataflake** [comment]
Apparently there's a `standard_error_message` that will then get invoked to try and handle the error. But the real problem seems to be the converted database. Are you 100% sure the conversion went correct and all records are good?

```
2019-05-09 11:29:20 - ERROR [ZODB.Connection] Couldn't load state for Products.zms.zms.ZMS 0x16ad35
Traceback (most recent call last):
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/Connection.py", line 795, in setstate
    self._reader.setGhostState(obj, p)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/serialize.py", line 633, in setGhostState
    state = self.getState(pickle)
  File "/Users/dwt/.virtualenvs/zope-zms-py3/lib/python3.7/site-packages/ZODB/serialize.py", line 626, in getState
    return unpickler.load()
_pickle.UnpicklingError: invalid load key, ''.
```

**Comment by d-maurer** [comment]
?rekcäH nitraM? wrote at 2019-5-9 02:58 -0700:
>While inspecting a database converted from python 2 to python 3 I noticed this unusual error handling strategy from zope. If I parse that correctly, then an error happens while handling the exception, which triggers an exception which then fails trying to start the wsgi response.

You parse that correctly. And from my point of view, it does not
seem "unusual".

Simplified, you have the following structure:
```
    try: ... process request ...
    except Exception as request_exc:
      try: ... handle exception ...
      except Exception as exception_exc:
        ... inform about both exceptions, because we are not sure
	that the lower framework layers do this in the way our
	users expect this (they might use a different log file, for
	example)...
	raise # pass the exception to the lower framework layers
```

Under Python 3, you might see the information about *request_exc*
twice. The reason: unlike Python 2, Python 3 supports directly
secondary exceptions (i.e. exceptions raised during the handling
of an exception). Potentially, the current code to display
the information for *exception_exc* does not yet take this into
account and reports about *request_exc* again, even though this
already has been done.

**Comment by dataflake** [comment]
@dwt Does that answer your question? If yes, I can close this.

**Comment by dwt** [comment]
Yes, I think that does answer it. 

For context: The conversion definitely didn't go through correctly and I was looking at this thinking that  this might have unearthed an error in the error handling of zope - so glad there's nothing there.
