### ISSUE TITLE
Minimum buildout.cfg is not enough

### ISSUE THREAD

**Issue by icemac** [zopefoundation/Zope#664]
history:
```
 2161  python3.8 -m venv zope
 2162  cd zope 
 2164  cp ../buildout.cfg .
 2165  bin/pip install -U pip zc.buildout
 2166  bin/buildout
 2167  bin/mkwsgiinstance 
 2168  vim etc/zope.ini
 2169  bin/runwsgi -v etc/zope.ini

```
and buildout.cfg:

```
[buildout]
extends = https://zopefoundation.github.io/Zope/releases/4.1/versions-prod.cfg
parts = zopescripts

[zopescripts]
recipe = zc.recipe.egg
interpreter = zopepy
eggs =
  Zope
#  Paste
  Products.TemporaryFolder
  Products.ExternalMethod
  Products.PythonScripts
  Products.Sessions
  Products.SiteErrorLog
  Products.MailHost
  Products.ZSQLMethods
  Products.ZMySQLDA

```

_Originally posted by @ghiodor in https://github.com/zopefoundation/Zope/issues/452#issuecomment-506225698_

**Comment by icemac** [comment]
Even using the minimum [buildout.cfg from the documentation](https://zope.readthedocs.io/en/latest/INSTALL.html#minimum-configuration) is not enough.

The traceback is:

```python
Traceback (most recent call last):
  File "bin/runwsgi", line 85, in <module>
    sys.exit(Zope2.Startup.serve.main())
  File "/.../Zope-4.1-py3.8.egg/Zope2/Startup/serve.py", line 248, in main
    return command.run()
  File "/.../Zope-4.1-py3.8.egg/Zope2/Startup/serve.py", line 188, in run
    app = self.loadapp(app_spec, name=app_name, relative_to=base,
  File "/.../Zope-4.1-py3.8.egg/Zope2/Startup/serve.py", line 217, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 275, in loadobj
    context = loadcontext(
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 299, in loadcontext
    return _loaders[scheme](
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 326, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 452, in get_context
    context = self._pipeline_app_context(
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 565, in _pipeline_app_context
    context.filter_contexts = [
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 566, in <listcomp>
    self.get_context(FILTER, name, global_conf)
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 457, in get_context
    context = self._context_from_use(
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 480, in _context_from_use
    context = self.get_context(
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 410, in get_context
    return loadcontext(object_type, name,
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 299, in loadcontext
    return _loaders[scheme](
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 334, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 624, in get_context
    entry_point, protocol, ep_name = self.find_egg_entry_point(
  File "/.../PasteDeploy-2.0.1-py3.8.egg/paste/deploy/loadwsgi.py", line 645, in find_egg_entry_point
    pkg_resources.require(self.spec)
  File "/.../zope/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/.../zope/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Paste' distribution was not found and is required by the application
```

**Comment by icemac** [comment]
The reason for the traceback is that the generated `etc/zope.ini` has:

```ini
[filter:translogger]
use = egg:Paste#translogger
setup_console_handler = False
```

Possible solutions I can think of:

* Include `Paste` in the minimum buildout.cfg example in the documentation
* Include `Paste` in `install_requires` in `setup.py`.

Are there any other ideas? Which solution do you prefer?

**Comment by dataflake** [comment]
I have added it to the minimum buildout in f4fd6b64da6a52ce16b10aa5cf4d4de58b016188.

It should not be in `install_requires` because Zope itself has no dependency on it. The dependency is from the default WSGI configuration template.

The translogger configuration should remain in the default WSGI template because that way you have something usable out of the box.

**Comment by icemac** [comment]
@dataflake I like your decision!

**Comment by ghiodor** [comment]
I understand the reasoning not to choose the other options, but having Paste in the minimum buildout also looks mysterious to me. Is the translogger a package? can this package not have Paste as a requirement?

**Comment by dataflake** [comment]
translogger is provided by Paste. It's not a separate thing.
