### ISSUE TITLE
Zope2 4.x does not provide XML-RPC folder listings

### ISSUE THREAD

**Issue by Rudd-O** [zopefoundation/Zope#76]
I create a BTreeFolder2 named "folder".  Then I do this:

```
Python 2.7.12 (default, Sep  2 2016, 14:46:00) 
[GCC 6.1.1 20160621 (Red Hat 6.1.1-3)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import xmlrpclib
>>> s = xmlrpclib.Server("http://localhost:8080/")
>>> s.folder.objectIds()
```

This happens:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for localhost:8080/: 404 Not Found>
```

This used to work.  What happened?

**Comment by Rudd-O** [comment]
For the record, I can tell that the `objectIds()` method exists and that it is declared with proper permissions (the opposite of which would not explain why it returns 404).

**Comment by Rudd-O** [comment]
There doesn't appear to be other methods that work to get the listing.  This one "works" (fails as anonymous):

```
>>> s.folder.getBatchObjectListing()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1331, in single_request
    response.msg,
xmlrpclib.ProtocolError: <ProtocolError for localhost:8080/: 401 Unauthorized>
```

**Comment by hannosch** [comment]
@Rudd-O If you want xmlrpc support, you need to install the ZServer package and keep running Zope using ZServer.

**Comment by Rudd-O** [comment]
Understood.  Thanks.  How does Zope2 4.x integrate extra packages like
ZServer?  I only see a WSGI running option.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by Rudd-O** [comment]
Wait, XML-RPC DID work for some methods!  With WSGI!
