### ISSUE TITLE
Error while using rfrefs

### ISSUE THREAD

**Issue by georgpfolz** [zopefoundation/Zope#795]
I tried to use rfrefs on a ZODB database and got the following error:

```
Traceback (most recent call last):
  File "bin/fsrefs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/opt/Zope4/lib/python2.7/site-packages/ZODB/scripts/fsrefs.py", line 139, in main
    refs = get_refs(data)
  File "/usr/local/opt/Zope4/lib/python2.7/site-packages/ZODB/serialize.py", line 707, in get_refs
    if not isinstance(oid, bytes):
UnboundLocalError: local variable 'oid' referenced before assignment
```

(Zope: 4.2, using Python 2.7.17)

**Comment by jugmac00** [comment]
This is a known bug in ZODB and there is already a PR, see https://github.com/zopefoundation/ZODB/pull/295
