### ISSUE TITLE
WebDAV: AttributeError: 'RequestContainer' object has no attribute 'PrincipiaSearchSource'

### ISSUE THREAD

**Issue by zopyx** [zopefoundation/Zope#799]
Using cadaver as WebDAV client to "edit nonexistingfile" performs three requests

```
127.0.0.1 - admin [05/Mar/2020:12:08:22 +0200] "OPTIONS /foo/m HTTP/1.1" 200 0 "-" "cadaver/0.23.3 neon/0.30.2"
127.0.0.1 - admin [05/Mar/2020:12:08:22 +0200] "LOCK /foo/m HTTP/1.1" 201 448 "-" "cadaver/0.23.3 neon/0.30.2"
127.0.0.1 - admin [05/Mar/2020:12:08:22 +0200] "PROPFIND /foo/m HTTP/1.1" 207 297 "-" "cadaver/0.23.3 neon/0.30.2"
```

Error:

```
2020-03-05 12:08:22 ERROR [waitress:357][waitress] Exception while serving /foo/m
Traceback (most recent call last):
  File "/home/ajung/src/zope/lib/python3.7/site-packages/waitress/channel.py", line 349, in service
    task.service()
  File "/home/ajung/src/zope/lib/python3.7/site-packages/waitress/task.py", line 169, in service
    self.execute()
  File "/home/ajung/src/zope/lib/python3.7/site-packages/waitress/task.py", line 439, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/ZPublisher/httpexceptions.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/ZPublisher/WSGIPublisher.py", line 364, in publish_module
    response = _publish(request, new_mod_info)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/ZPublisher/WSGIPublisher.py", line 267, in publish
    bind=1)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/ZPublisher/mapply.py", line 85, in mapply
    return debug(object, args, context)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/ZPublisher/WSGIPublisher.py", line 68, in call_object
    return obj(*args)
  File "/home/ajung/src/zope/lib/python3.7/site-packages/webdav/Resource.py", line 680, in manage_DAVget
    return self.PrincipiaSearchSource()
AttributeError: 'RequestContainer' object has no attribute 'PrincipiaSearchSource'

```

**Comment by zopyx** [comment]
Suggested fix:

```
    @security.protected(webdav_access)
    def manage_DAVget(self):
        """Gets the document source"""
        # The default implementation calls PrincipiaSearchSource
        try:
            return self.PrincipiaSearchSource()
        except AttributeError:
            return ''
```
