### ISSUE TITLE
Failed Run Zope According Zope Developer’s Guide 

### ISSUE THREAD

**Issue by zhangliangnbu** [zopefoundation/Zope#958]
### What I did:

I'm learning Zope by Zope Developer’s Guide：https://zope.readthedocs.io/en/latest/zdgbook/GettingStarted.html
In part "Getting Started", when I  execute `$ bin/runwsgi etc/zope.ini`，error occurred. Every step is well excepte this.
The only difference between what I did with the document is that，the document use zope 4, and I use zope 5. 
My File Tree:
```
.
├── poll_build
│   ├── bin
│   │   ├── addzopeuser
│   │   ├── mkwsgiinstance
│   │   ├── runwsgi
│   │   ├── zconsole
│   │   └── zopepy
│   ├── buildout.cfg
│   ├── develop-eggs
│   │   └── poll.main.egg-link
│   ├── eggs
│   │   └── zc.recipe.egg-2.0.7-py3.7.egg
│   │       ├── EGG-INFO
│   │       │   ├── dependency_links.txt
│   │       │   ├── entry_points.txt
│   │       │   ├── namespace_packages.txt
│   │       │   ├── not-zip-safe
│   │       │   ├── PKG-INFO
│   │       │   ├── requires.txt
│   │       │   ├── SOURCES.txt
│   │       │   └── top_level.txt
│   │       └── zc
│   │           ├── __init__.py
│   │           ├── __pycache__
│   │           └── recipe
│   ├── etc
│   │   ├── site.zcml
│   │   ├── zope.conf
│   │   └── zope.ini
│   ├── parts
│   └── var
│       ├── cache
│       │   ├── 05b3e9dc4dba5f00cee74ad2dea822a2.py
│       │   ├── 36dc298c645cb5f36e2820b23b7d470e.py
│       │   ├── 56784e64b51b25256bd8c975616efeeb.py
│       │   ├── 5f0f2b53741e9ef3199ff6778a128221.py
│       │   ├── 720afc96a00495044b16c0983de30c43.py
│       │   ├── __pycache__
│       │   │   ├── 05b3e9dc4dba5f00cee74ad2dea822a2.cpython-37.pyc
│       │   │   ├── 36dc298c645cb5f36e2820b23b7d470e.cpython-37.pyc
│       │   │   ├── 56784e64b51b25256bd8c975616efeeb.cpython-37.pyc
│       │   │   ├── 5f0f2b53741e9ef3199ff6778a128221.cpython-37.pyc
│       │   │   └── 720afc96a00495044b16c0983de30c43.cpython-37.pyc
│       │   └── README.txt
│       ├── Data.fs
│       ├── Data.fs.index
│       ├── Data.fs.lock
│       ├── Data.fs.tmp
│       ├── log
│       │   ├── event.log
│       │   ├── README.txt
│       │   └── Z4.log
│       └── README.txt
└── poll.main
    ├── setup.py
    └── src
        ├── poll
        │   ├── __init__.py
        │   └── main
        │       ├── app.py
        │       ├── configure.zcml
        │       ├── __init__.py
        │       └── manage_addPollMain_form.zpt
        └── poll.main.egg-info
            ├── dependency_links.txt
            ├── namespace_packages.txt
            ├── PKG-INFO
            ├── requires.txt
            ├── SOURCES.txt
            └── top_level.txt

```

The `poll_build/buildout.cfg` :
```
[buildout]
develop = ../poll.main
extends =
    https://zopefoundation.github.io/Zope/releases/5.0/versions-prod.cfg
parts =
    zopescripts

[zopescripts]
recipe = zc.recipe.egg
interpreter = zopepy
eggs =
    Zope
    Paste
    poll.main

```

The `poll_build/etc/site.zcml`:
```
<configure
    xmlns="http://namespaces.zope.org/zope"
    xmlns:meta="http://namespaces.zope.org/meta"
    xmlns:five="http://namespaces.zope.org/five">

  <include package="poll.main" />
  <include package="Zope2.App" />

  <!-- Load the meta -->
  <include files="package-includes/*-meta.zcml" />
  <five:loadProducts file="meta.zcml"/>

  <!-- Load the configuration -->
  <include files="package-includes/*-configure.zcml" />
  <five:loadProducts />

  <!-- Load the configuration overrides-->
  <includeOverrides files="package-includes/*-overrides.zcml" />
  <five:loadProductsOverrides />

</configure>

```

The content in `poll.main` directory is  exactly the same as the guide document.

### What I expect to happen:
The server is started, and no error occured

### What actually happened:
The server is not started, and error occured as below：
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 226, in resolve
    __import__(mname)
ModuleNotFoundError: No module named 'poll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/fields.py", line 172, in fromUnicode
    value = self.context.resolve(name)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 233, in resolve
    "ImportError: Couldn't import %s, %s" % (mname, v))
zope.configuration.exceptions.ConfigurationError: ImportError: Couldn't import poll, No module named 'poll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 1687, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/fields.py", line 174, in fromUnicode
    raise ValidationError(v).with_field_and_value(self, name)
zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import poll, No module named 'poll'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/zope/bin/runwsgi", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/Startup/serve.py", line 251, in main
    return command.run()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/Startup/serve.py", line 190, in run
    global_conf=vars)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/Startup/serve.py", line 220, in loadapp
    return loadapp(app_spec, name=name, relative_to=relative_to, **kw)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/Startup/run.py", line 60, in make_wsgi_app
    starter.prepare()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/Startup/starter.py", line 38, in prepare
    self.startZope()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/Startup/starter.py", line 94, in startZope
    Zope2.startup_wsgi()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/__init__.py", line 36, in startup_wsgi
    _startup()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/App/startup.py", line 126, in startup
    load_zcml()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/App/startup.py", line 41, in load_zcml
    load_site()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/Zope2/App/zcml.py", line 45, in load_site
    _context = xmlconfig.file(site_zcml)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 657, in file
    include(context, name, package)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 557, in include
    processxmlfile(f, context)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 407, in processxmlfile
    parser.parse(src)
  File "/root/miniconda3/envs/zope/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/root/miniconda3/envs/zope/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/root/miniconda3/envs/zope/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/tmp/build/80754af9/python_1614362349910/work/Modules/pyexpat.c", line 471, in EndElement
  File "/root/miniconda3/envs/zope/lib/python3.7/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 393, in endElementNS
    self._handle_exception(ex, info)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 868, in finish
    args = toargs(context, *self.argdata)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 1690, in toargs
    None, sys.exc_info()[2])
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/_compat.py", line 30, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/config.py", line 1687, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/root/miniconda3/envs/zope/lib/python3.7/site-packages/zope/configuration/fields.py", line 174, in fromUnicode
    raise ValidationError(v).with_field_and_value(self, name)
zope.configuration.exceptions.ConfigurationError: Invalid value for 'package'
    File "/root/poll/poll_build/etc/site.zcml", line 6.2-6.33
    zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import poll, No module named 'poll'

```

### What version of Python and Zope/Addons I am using:
- OS: CentOS 7.6
- Python 3.7.10
- Zope 5.0

Please Help Me, Thanks !!!

**Comment by zhangliangnbu** [comment]
Anyone can help ?

**Comment by d-maurer** [comment]
```
zope.configuration.exceptions.ConfigurationError: Invalid value for 'package'
    File "/root/poll/poll_build/etc/site.zcml", line 6.2-6.33
    zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import poll, No module named 'poll'
```
The error message tells you that the problem comes from line 6 of your `site.zcml` (which contains `include package="poll.main"` and is `no module named 'poll'`. Thus, your module `poll` is not available.

To understand why, I recommend the following steps:
 * start `bin/zopepy` (this starts an interactive Python interpreter) and try `import poll.main`. If this succeeds, `zopepy` knows about your `poll.main`. If it fails, look at the start of the `zopepy` script: you should see near the beginning a modification of  `sys.path` which contains (among others) your eggs. Rerun `bin/buildout` should this not be the case and then verify again.
 * look at the first line of the `runwsgi` script. It should contain a path to the `bin/zopepy` above.

**Comment by zhangliangnbu** [comment]
> ```
> zope.configuration.exceptions.ConfigurationError: Invalid value for 'package'
>     File "/root/poll/poll_build/etc/site.zcml", line 6.2-6.33
>     zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import poll, No module named 'poll'
> ```
> 
> The error message tells you that the problem comes from line 6 of your `site.zcml` (which contains `include package="poll.main"` and is `no module named 'poll'`. Thus, your module `poll` is not available.
> 
> To understand why, I recommend the following steps:
> 
> * start `bin/zopepy` (this starts an interactive Python interpreter) and try `import poll.main`. If this succeeds, `zopepy` knows about your `poll.main`. If it fails, look at the start of the `zopepy` script: you should see near the beginning a modification of  `sys.path` which contains (among others) your eggs. Rerun `bin/buildout` should this not be the case and then verify again.
> * look at the first line of the `runwsgi` script. It should contain a path to the `bin/zopepy` above.

Hi @d-maurer,  the `bin/zopy` is right, and I can import `poll.main`  after `run bin/zopepy`,  the script is: 
```
#!/root/miniconda3/envs/zope/bin/python

import sys

sys.path[0:0] = [
  '/root/poll/poll.main/src',
  '/root/miniconda3/envs/zope/lib/python3.7/site-packages',
  ]


_interactive = True
if len(sys.argv) > 1:
    _options, _args = __import__("getopt").getopt(sys.argv[1:], 'ic:m:')
    _interactive = False
    for (_opt, _val) in _options:
        if _opt == '-i':
            _interactive = True
        elif _opt == '-c':
            exec(_val)
        elif _opt == '-m':
            sys.argv[1:] = _args
            _args = []
            __import__("runpy").run_module(
                 _val, {}, "__main__", alter_sys=True)

    if _args:
        sys.argv[:] = _args
        __file__ = _args[0]
        del _options, _args
        with open(__file__) as __file__f:
            exec(compile(__file__f.read(), __file__, "exec"))

if _interactive:
    del _interactive
    __import__("code").interact(banner="", local=globals())
```

but  the `bin/runwsgi` script does not contain a path to the `bin/zopepy`, the detail is:
```
#!/root/miniconda3/envs/zope/bin/python

import sys
sys.path[0:0] = [
  '/root/poll/poll.main/src',
  '/root/miniconda3/envs/zope/lib/python3.7/site-packages',
  ]

import Zope2.Startup.serve

if __name__ == '__main__':
    sys.exit(Zope2.Startup.serve.main())

```
I dont know why....

**Comment by dataflake** [comment]
The problem here is where you add `<include package="poll.main" />` inside `poll_build/etc/site.zcml`. You must add it after `<include package="Zope2.App" />`. I'll update the documentation to be more clear.

**Comment by d-maurer** [comment]
章亮 wrote at 2021-4-13 23:24 -0700:
> ...
>> To understand why, I recommend the following steps:
>> ...
>> * look at the first line of the `runwsgi` script. It should contain a path to the `bin/zopepy` above.
>
>Hi @d-maurer,  the `bin/zopy` is right, and I can import `poll.main`  after `run bin/zopepy`,  the script is:
>```
>#!/root/miniconda3/envs/zope/bin/python
>
>import sys
>
>sys.path[0:0] = [
>  '/root/poll/poll.main/src',
>  '/root/miniconda3/envs/zope/lib/python3.7/site-packages',
>  ]
> ...
>but  the `bin/runwsgi` script does not contain a path to the `bin/zopepy`, the detail is:
>```
>#!/root/miniconda3/envs/zope/bin/python
>
>import sys
>sys.path[0:0] = [
>  '/root/poll/poll.main/src',
>  '/root/miniconda3/envs/zope/lib/python3.7/site-packages',
>  ]
>
>import Zope2.Startup.serve
>
>if __name__ == '__main__':
>    sys.exit(Zope2.Startup.serve.main())
>
>```
>I dont know why....

It contains the same `sys.path` extension as `zopepy`;
thus, it should be able to import `poll.main` (as `zopepy` does).
You could verify this by inserting an `import poll.main`
before the `import Zope2.Startup.serve`.

What you observe is a so called "startup problem".
In some cases, startup problems can be analysed with
`zconsole debug etc/zope.conf`.
`zconsole debug` starts Zope not as a web server but
in an interactive Python interpreter.
Should the Zope startup fail, it leaves you in an interactive
Python session where you can examine the state -- e.g.
try `import poll.main` and try to find out why it fails
(first step would be to look at `sys.path` and whether it contains
the `poll.main` reference).

**Comment by zhangliangnbu** [comment]
@dataflake @d-maurer Thanks a lot! I have solved it by putting `<include package="poll.main" />` after  `<include package="Zope2.App" />` .

**Comment by dataflake** [comment]
The instructions at https://zope.readthedocs.io/en/latest/zdgbook/GettingStarted.html have now been updated.

**Comment by zhangliangnbu** [comment]
@d-maurer @dataflake By the way, in fact I made two mistakes: 
1. I used `runwsgi etc/zope.ini`, then it throw error:  
```
zope.configuration.exceptions.ConfigurationError: Invalid value for 'package'
    File "/root/poll/poll_build/etc/site.zcml", line 6.2-6.33
    zope.schema._bootstrapinterfaces.ValidationError: ImportError: Couldn't import poll, No module named 'poll'
```
this `runwsgi ` located at `/root/miniconda3/envs/zope/bin/runwsgi`, not at current `poll/poll_build/bin` directory. I realized this problem today, then I use `bin/runwsgi` .

2.  When I used `bin/runwsgi etc/zope.ini`, then it throw error:
```
zope.configuration.exceptions.ConfigurationError: ('Unknown directive', 'http://namespaces.zope.org/five', 'registerPackage')
    File "/projects/poll/poll_build/etc/site.zcml", line 7.2-7.33
    File "/projects/poll/poll.main/src/poll/main/configure.zcml", line 3.2
```
this is the real problem what the wrong order of ` <include package="poll.main" />`  cause.
